### ISSUE TITLE
May I ask if there are implementations of MetaBBO baselines ?

### ISSUE THREAD

**Issue by hexiao5886** [GMC-DRL/Symbol#3]

**Comment by JC-Chen1** [comment]
Hi! For MetaBBO baselines' implementation, I would recommend to access [MetaBox](https://github.com/GMC-DRL/MetaBox), which is a benchmark platform of MetaBBO methods, we released it last year. You would find several existing MetaBBO methods in MetaBox. For those not implemented in MetaBox, you could access them in their public codebase.

**Comment by hexiao5886** [comment]
Sincere thanks for your reply!  I'll go for a look.
